export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";
export const POST_VOLUNTERR_SUCCESS = "POST_VOLUNTERR_SUCCESS";
export const POST_VOLUNTERR_FAIL = "POST_VOLUNTERR_FAIL";

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const ALL_NEWS_FAIL = 'ALL_NEWS_FAIL'
export const ALL_NEWS_SUCCESS = 'ALL_NEWS_SUCCESS'
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS'

export const ALL_EVENTS_FAIL = 'ALL_EVENTS_FAIL'
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'


export const ALL_CAUSE_FAIL = 'ALL_CAUSE_FAIL'
export const EDIT_CAUSE_SUCCESS = 'EDIT_CAUSE_SUCCESS'
export const ALL_CAUSE_SUCCESS = 'ALL_CAUSE_SUCCESS'

export const SINGUP_SUCCESS = "SINGUP_SUCCESS";
export const SINGUP_FAIL = "SINGUP_FAIL";


// ---------------
export const ALL_COMPAIGN_FAIL = 'ALL_COMPAIGN_FAIL'
export const ALL_COMPAIGN_SUCCESS = 'ALL_COMPAIGN_SUCCESS'
export const EDIT_COMPAIGN_SUCCESS = 'EDIT_COMPAIGN_SUCCESS'

export const ALL_DONATION_PRODUCT_SUCCESS = 'ALL_DONATION_PRODUCT_SUCCESS'
export const ALL_DONATION_PRODUCT_FAIL = 'ALL_DONATION_PRODUCT_FAIL'

export const ALL_DONATION_PRODUCT_HISTORY_SUCCESS = 'ALL_DONATION_PRODUCT_HISTORY_SUCCESS'
export const ALL_DONATION_PRODUCT_HISTORY_FAIL = 'ALL_DONATION_PRODUCT_HISTORY_FAIL'

export const ALL_OUR_PRODUCT_SUCCESS = 'ALL_OUR_PRODUCT_SUCCESS'
export const ALL_OUR_PRODUCT_FAIL = 'ALL_OUR_PRODUCT_FAIL'



export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'

export const INCREASE_ITEM = 'INCREASE_ITEM'
export const DETIAL_INCREASE_ITEM = 'DETIAL_INCREASE_ITEM'

export const DETIAL_DECREASE_ITEM = 'DETIAL_DECREASE_ITEM'
export const DECREASE_ITEM = 'DECREASE_ITEM'

export const CLEAR_CART = 'CLEAR_CART'
export const DETIAL_ITEM = 'DETIAL_ITEM'

export const ADDTOCART = 'ADDTOCART'
export const ADD_WISHLIST_PRODUCT = 'ADD_WISHLIST_PRODUCT'

export const INCREASE_WISHLIST_PRODUCT = 'INCREASE_WISHLIST_PRODUCT'
export const DECREASE_WISHLIST_PRODCUT = 'DECREASE_WISHLIST_PRODCUT'

export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM'
export const ADD_MODAL_PRODUCT = 'ADD_MODAL_PRODUCT'

export const MODAL_INCREASE_ITEM = 'MODAL_INCREASE_ITEM'
export const MODAL_DECREASE_ITEM = 'MODAL_DECREASE_ITEM'

export const REQUEST_BUTTON_CLICK = 'REQUEST_BUTTON_CLICK'
export const DONATION_PRODUCT_REQUEST = 'DONATION_PRODUCT_REQUEST'
export const NEWS_DETAIL = 'NEWS_DETAIL'
export const COMPAIGN_DETAIL = 'COMPAIGN_DETAIL'

