export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";
export const POST_VOLUNTERR_SUCCESS = "POST_VOLUNTERR_SUCCESS";
export const POST_VOLUNTERR_FAIL = "POST_VOLUNTERR_FAIL";

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const ALL_NEWS_FAIL = 'ALL_NEWS_FAIL'
export const ALL_NEWS_SUCCESS = 'ALL_NEWS_SUCCESS'
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS'

export const ALL_EVENTS_FAIL = 'ALL_EVENTS_FAIL'
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'


export const ALL_CAUSE_FAIL = 'ALL_CAUSE_FAIL'
export const EDIT_CAUSE_SUCCESS = 'EDIT_CAUSE_SUCCESS'
export const ALL_CAUSE_SUCCESS = 'ALL_CAUSE_SUCCESS'

export const SINGUP_SUCCESS = "SINGUP_SUCCESS";
export const SINGUP_FAIL = "SINGUP_FAIL";

